hackathon/accounts/urls.py
from django.urls import path, include
from . import views
from .views import profile_view, edit_profile_view


app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("afterlogin/", views.after_login_view, name="afterlogin"),
    path("board/", include("board.urls")),
    path("profile/", views.profile_view, name="profile"),
    path("profile/edit/", views.edit_profile_view, name='edit_profile_view'),
    path("find_id/", views.find_id_view, name="find_id"),
    path("find_pw/", views.find_pw_view, name="find_pw"),
    path("reset_pw/", views.reset_pw_view, name="reset_pw"),
]

hackathon/board/urls.py
from django.urls import path
from .views import *

app_name = 'board'
urlpatterns = [
    path('list/', board_list, name='board_list'),
    path('write/', board_write, name='board_write'),
    path('update/', board_update, name='board_update'),
    path('detail/<int:pk>/', board_detail, name='board_detail'),
    path('modify/<int:pk>/', board_modify, name='board_modify'),
]

hackathon/hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import homepage_view

app_name = "hackathon"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view, name='homepage_view'),
    path('auth/', include("accounts.urls")),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hackathon/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User

class User(AbstractUser):
    gender = models.CharField(max_length=5, verbose_name="성별")
    address_si = models.CharField(max_length=50, verbose_name="거주지(시)")
    address_gu = models.CharField(max_length=50, verbose_name="거주지(구)")
    address_dong = models.CharField(max_length=50, verbose_name="거주지(동)")
    resi_num = models.CharField(max_length=30, verbose_name="주민등록번호")
    ph_num = models.CharField(max_length=30, verbose_name="전화번호")
    nickname = models.CharField(max_length=50, verbose_name="닉네임")
    resi_img = models.ImageField(null=True, verbose_name="주민등록증 사진", upload_to='users/')
    present_img = models.ImageField(null=True, verbose_name="현재 사진", upload_to='users/')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    ph_num = models.CharField(max_length=20)
    nickname = models.CharField(max_length=30)

    def __str__(self):
        return self.user.username

hackathon/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm

from .models import Profile, User


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', )

    address = forms.CharField(max_length=255, required=True)
    ph_num = forms.CharField(max_length=20, required=True)
    nickname = forms.CharField(max_length=30, required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        profile = self.user.profile
        self.fields['address'].widget.attrs.update({'value': profile.address})
        self.fields['ph_num'].widget.attrs.update({'value': profile.ph_num})
        self.fields['nickname'].widget.attrs.update({'value': profile.nickname})

        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field and isinstance(field, forms.CharField):
                field.widget.attrs.update({'class': 'form-control'})

hackathon/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import User
#프로필 수정 오버라이드
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model 



from .forms import EditProfileForm

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증성공")
            login(request, user)
            return render(request, "accounts/afterlogin.html")
        else:
            print("인증실패")
    return render(request, "accounts/login.html")

def logout_view(request):
    logout(request)
    return redirect("homepage_view")

def find_id_view(request):
    if request.method == "POST":
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        ph_num = request.POST["ph_num"]

        try:
            user = User.objects.get(Q(first_name=firstname) & Q(last_name=lastname) & Q(ph_num=ph_num))
            print("회원정보 일치")
            messages.info(request, f"회원정보 일치 : 아이디는 {user.username} 입니다.")
        except User.DoesNotExist:
            print("회원정보 불일치")
            messages.error(request, "회원정보 불일치 : 해당 정보로 등록된 계정이 없습니다.")

    return render(request, "accounts/find_id.html")


def find_pw_view(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        ph_num = request.POST.get("ph_num")
        resi_num = request.POST.get("resi_num")
        
        try:
            user = User.objects.get(
                Q(first_name=first_name) & Q(last_name=last_name) &
                Q(ph_num=ph_num) & Q(resi_num=resi_num))
            print("회원정보일치")
            messages.info(request, "회원정보 일치 : 비밀번호 초기화를 진행합니다.")
            return render(request, "accounts/reset_pw.html")
        except User.DoesNotExist:
            print("회원정보불일치")
            messages.error(request, "회원정보 불일치 : 해당 정보로 등록된 계정이 없습니다.")

    return render(request, "accounts/find_pw.html")



def reset_pw_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")

        if password == password2:
            User = get_user_model()
            user = User.objects.get(username=username)
            user.set_password(password)
            user.save()

            messages.info(request, '비밀번호가 성공적으로 변경되었습니다.')
            return redirect("accounts:login")
            
        else:
            messages.error(request, '사용자를 찾을 수 없습니다.')

    return render(request, 'accounts/reset_pw.html')


   

def signup_view(request):
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        password2 = request.POST["password2"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        gender = request.POST["gender"]
        address_si = request.POST["address_si"]
        address_gu = request.POST["address_gu"]
        address_dong = request.POST["address_dong"]
        resi_num = request.POST["resi_num"]
        ph_num = request.POST["ph_num"]
        nickname = request.POST["nickname"]
        resi_img = request.FILES["resi_img"]
        present_img = request.FILES["present_img"]

        if password == password2:
            user =  User.objects.create_user(username, email, password)
            user.last_name = lastname
            user.first_name = firstname
            user.gender = gender
            user.address_si = address_si
            user.address_gu = address_gu
            user.address_dong = address_dong
            user.gender = gender
            user.ph_num = ph_num
            user.resi_num = resi_num
            user.nickname = nickname
            user.resi_img = resi_img
            user.present_img = present_img
            user.save()
            return redirect("accounts:login")
        else:
            return redirect("accounts:signup")
        

        
    return render(request, "accounts/signup.html")

def homepage_view(request):
    return render(request, "accounts/homepage.html")

def after_login_view(request):
    return render(request, "accounts/afterlogin.html")

#프로필 파트

def profile(request):
    # 프로필 템플릿을 렌더링합니다.
    return render(request, "accounts/profile.html")

@login_required
def profile_info(request):
    user = request.user
    # 유저의 정보를 처리하여 profile_info.html에 전달
    context = {
       'user': user,
     }
    return render(request, "accounts/profile_info.html", context)

def profile_view(request):
    user = request.user
    context = {
        # 템플릿에서 사용할 변수 값들
        'user': user,
        'profile_info': profile_info,
     }
    return render(request, "accounts/profile_info.html", {"user": user})

#프로필 수정 파트

def edit_profile(request):
    # 프로필 수정 템플릿을 렌더링합니다.
    return render(request, "accounts/profile/edit.html")

@login_required
def edit_profile_view(request):
    user = request.user
    if request.method == "POST":
        user.first_name = request.POST.get("first_name", "")
        user.last_name = request.POST.get("last_name", "")
        user.email = request.POST.get("email", "")
        user.address = request.POST.get("address", "")
        user.ph_num = request.POST.get("ph_num", "")
        user.nickname = request.POST.get("nickname", "")
        user.save()
        return redirect("accounts:profile")
    return render(request, "accounts/edit_profile.html", {"user": user})

class EditProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/edit_profile.html'
    form_class = EditProfileForm
    success_url = reverse_lazy('accounts:profile')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

    def get_initial(self):
        initial = super().get_initial()
        user = self.request.user
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        initial['email'] = user.email
        initial['address'] = user.profile.address
        initial['ph_num'] = user.profile.ph_num
        initial['nickname'] = user.profile.nickname
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.email = form.cleaned_data['email']
        user.profile.address = form.cleaned_data['address']
        user.profile.ph_num = form.cleaned_data['ph_num']
        user.profile.nickname = form.cleaned_data['nickname']
        user.save()

        profile = user.profile
        profile.phone_number = form.cleaned_data['phone_number']
        profile.website = form.cleaned_data['website']
        profile.save()

        return super().form_valid(form)

hackathon/templates/accounts/afterlogin.html
<!doctype html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>돌쇠야</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <div class="container">
      <header>
        <p>돌쇠야</p>
        <ul>
          {% if User.is_authenticated %}
          <li><a href="{% url 'accounts:afterlogin'%}">홈</a></li>
          {% else % }
          <li><a href="{% url 'accounts:homepage'%}">홈</a></li>
          {% endif %}
          <li>{{ user.username }}님</a></li>
          <li><a href="{% url 'accounts:logout'%}">로그아웃</a></li>
        </ul>
      </header>
      <section>
        <a href="{% url 'accounts:board:board_list'%}">게시판</a>
      </section>
      <footer>
        Cover template for <a href="https://twitter.com/mdo">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.
      </footer>
    </div>
    
  </body>
</html>

hackathon/templates/accounts/edit_profile.html
<!DOCTYPE html>
<html>
<head>
    <title>프로필 수정</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            width: 350px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .group {
            margin-bottom: 16px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button[type="submit"] {
            background-color: #000;
            color: white;
            border: none;
            padding: 10px 16px;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button[type="submit"]:hover {
            background-color: #444;
        }

    </style>
</head>
<body>
    <div class="container">
        <h2>프로필 수정</h2>
        <form method="post">
            {% csrf_token %}
            <div class="group">
                <label for="username">아이디:</label>
                <input type="text" name="username" value="{{ user.username }}" required>
            </div>
            <div class="group">
                <label for="first_name">이름:</label>
                <input type="text" name="first_name" value="{{ user.first_name }}" required>
            </div>
            <div class="group">
                <label for="last_name">성:</label>
                <input type="text" name="last_name" value="{{ user.last_name }}" required>
            </div>
            <div class="group">
                <label for="nickname">닉네임:</label>
                <input type="text" name="nickname" value="{{ user.nickname }}" required>
            </div>
            <div class="group">
                <label for="email">이메일:</label>
                <input type="email" name="email" value="{{ user.email }}" required>
            </div>
            <div class="group">
                <label for="address_si">주소(시):</label>
                <input type="text" name="address_si" value="{{ user.address_si }}">
            </div>
            <div class="group">
                <label for="address_dong">주소(동):</label>
                <input type="text" name="address_dong" value="{{ user.address_dong }}">
            </div>
            <div class="group">
                <label for="ph_num">전화번호:</label>
                <input type="text" name="ph_num" value="{{ user.ph_num }}">
            </div>
            <button type="submit">저장</button>
        </form>
    </div>
</body>
</html>

hackathon/templates/accounts/find_id.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>아이디 찾기</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
        html, body {
            height: 100%;
        }
        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }
        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.25);
        }
        .form-signin .checkbox {
            font-weight: 400;
            font-size: 14px;
            color: #596069;
            margin-top: 10px;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
            margin-bottom: 15px;
            border-radius: 20px;
            font-family: 'Noto Sans KR', sans-serif;
            border: 1px solid #d9dadb;
        }
        .form-signin label {
            display: block;
            margin-bottom: 5px;
            color: #73777a;
        }
        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-radius: 20px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
            border-top: none;
            border-left: none;
            border-right: none;
        }
        .form-signin input[type="text"]:focus,
        .form-signin input[type="password"]:focus {
            outline: none;
            box-shadow: none;
        }
        .form-signin input[type="submit"] {
            margin-top: 30px;
            border-radius: 20px;
            background-color: #6db433;
            border-color: #5ba82e;
            font-size: 18px;
            padding: 10px 20px;
        }
        .form-signin input[type="submit"]:hover {
            background-color: #5ba82e;
            border-color: #4b8d24;
        }
        .form-signin h1,
        .form-signin a,
        .form-signin p {
            text-align: center;
            font-family: 'Noto Sans KR', sans-serif;
        }
        .form-signin h1 {
            font-size: 32px;
            margin-bottom: 20px;
            color: #5ba82e;
        }
        .form-signin a {
            color: #5ba82e;
            font-size: 14px;
            text-decoration: none;
            margin-bottom: 10px;
            display: block;
        }
        .form-signin p {
            font-size: 14px;
            margin-top: 15px;
            color: #73777a;
        }
    </style>

</head>
<body class="text-center">

<form class="form-signin" action="" method="POST">
    {% csrf_token %}
    <img class="mb-4" src="https://toss.im/assets/img/svg/toss_logo_horizontal.svg" alt="" width="200">

    <h1 class="h3 mb-3 font-weight-normal">아이디 찾기</h1>

    <label for="lastname">성</label>
    <input type="text" name="lastname" class="form-control" placeholder="성" required autofocus>
    <label for="firstname">이름</label>
    <input type="text" name="firstname" class="form-control" placeholder="이름" required>
    <label for="ph_num">전화번호</label>
    <input type="text" name="ph_num" class="form-control" placeholder="전화번호" required>



    <button class="btn btn-lg btn-primary btn-block" type="submit">아이디 찾기</button>

    <a href="{% url 'accounts:find_pw' %}">비밀번호 찾기</a>
    <a href="{% url 'homepage_view' %}">홈페이지</a>
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>


    <p class="mt-5 mb-3 text-muted">&copy; 2023</p>
</form>

<!-- 팝업 메시지 -->
{% if messages %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            {% for message in messages %}
                alert('{{ message }}');
            {% endfor %}
        });
    </script>
{% endif %}

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"><\/script>')</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/Sc4p7SzpDQ+oNyMI5W+9pGczwwEA+NmPj" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Font Awesome -->
<script src="https://kit.fontawesome.com/14163a0893.js" crossorigin="anonymous"></script>

<!-- Ajax CDN -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</body>
</html>

hackathon/templates/accounts/find_pw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>비밀번호 찾기</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
        html, body {
            height: 100%;
        }
        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }
        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.25);
        }
        .form-signin .checkbox {
            font-weight: 400;
            font-size: 14px;
            color: #596069;
            margin-top: 10px;
        }
        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
            margin-bottom: 15px;
            border-radius: 20px;
            font-family: 'Noto Sans KR', sans-serif;
            border: 1px solid #d9dadb;
        }
        .form-signin label {
            display: block;
            margin-bottom: 5px;
            color: #73777a;
        }
        .form-signin input[type="text"],
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-radius: 20px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
            border-top: none;
            border-left: none;
            border-right: none;
        }
        .form-signin input[type="text"]:focus,
        .form-signin input[type="password"]:focus {
            outline: none;
            box-shadow: none;
        }
        .form-signin input[type="submit"] {
            margin-top: 30px;
            border-radius: 20px;
            background-color: #6db433;
            border-color: #5ba82e;
            font-size: 18px;
            padding: 10px 20px;
        }
        .form-signin input[type="submit"]:hover {
            background-color: #5ba82e;
            border-color: #4b8d24;
        }
        .form-signin h1,
        .form-signin a,
        .form-signin p {
            text-align: center;
            font-family: 'Noto Sans KR', sans-serif;
        }
        .form-signin h1 {
            font-size: 32px;
            margin-bottom: 20px;
            color: #5ba82e;
        }
        .form-signin a {
            color: #5ba82e;
            font-size: 14px;
            text-decoration: none;
            margin-bottom: 10px;
            display: block;
        }
        .form-signin p {
            font-size: 14px;
            margin-top: 15px;
            color: #73777a;
        }
    </style>

</head>
<body class="text-center">

<form class="form-signin" action="" method="POST">
    {% csrf_token %}
    <img class="mb-4" src="https://toss.im/assets/img/svg/toss_logo_horizontal.svg" alt="" width="200">

    <h1 class="h3 mb-3 font-weight-normal">비밀번호 찾기</h1>

    <label for="first_name">이름</label>
    <input type="text" name="first_name" class="form-control" placeholder="성" required autofocus>
    <label for="last_name">이름</label>
    <input type="text" name="last_name" class="form-control" placeholder="이름" required>
    <label for="ph_num">전화번호</label>
    <input type="text" name="ph_num" class="form-control" placeholder="전화번호" required>
    <label for="resi_num">주민번호</label>
    <input type="text" name="resi_num" class="form-control" placeholder="주민번호" required>



    <button class="btn btn-lg btn-primary btn-block" type="submit">비밀번호 찾기</button>

    <a href="{% url 'accounts:find_id' %}">아이디 찾기</a>
    <a href="{% url 'homepage_view' %}">홈페이지</a>
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>


    <p class="mt-5 mb-3 text-muted">&copy; 2023</p>
</form>

<!-- 팝업 메시지 -->
{% if messages %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            {% for message in messages %}
                alert('{{ message }}');
            {% endfor %}

            $('#popupConfirmButton').on('click', function() {
                var redirectToLogin = false; 
                {% for message in messages %}
                    {% if '회원정보일치' in message %}
                        redirectToLogin = true;
                        break; 
                    {% endif %}
                {% endfor %}

                if (redirectToLogin) {
                    window.location.href = "{% url 'accounts:login' %}";
                } else {
                }
            });
        });
    </script>
{% endif %}


<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"><\/script>')</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/Sc4p7SzpDQ+oNyMI5W+9pGczwwEA+NmPj" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Font Awesome -->
<script src="https://kit.fontawesome.com/14163a0893.js" crossorigin="anonymous"></script>

<!-- Ajax CDN -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</body>
</html>